### PR TITLE
Rabbits hole

### PR DESCRIPTION
**Pull request by kashesandr**

### CODE REVIEW

**Comment by diastremskii** [comment]
Ooops, I don't get it :(

At first I thought what value - hash of last commit(2dfdbc3...) and I should find some sort of task in DatArt repository lower on Git tree from [here](https://github.com/DataArt/chip-in-calculator/commit/2dfdbc347851f3edeb114b167912413654f8c6a3). But then I realized what I can't go to commit children, only to parents. 

Maybe I'm overthinking it...

**Comment by kashesandr** [comment]
Have you tried going to live?

**Comment by diastremskii** [comment]
Oh wow, I even forgot about live version and thought what I should find entrance to rabbit's hole in "orphaned" commits.

**Comment by diastremskii** [comment]
[Anyway, here's gist with solution.](https://gist.github.com/TheBeastOfCaerbannog/5c9aed4ee81016f02f6755090685022d) Looks ugly, but I really wanted one-liner :)

**Comment by kashesandr** [comment]
@TheBeastOfCaerbannog looks fine! So, please if you're interested. Do what is in the instructions that you've decoded :)

**Comment by diastremskii** [comment]
@kashesandr Yep, I am interested and already sent e-mail :)

**Pull request closed without merging**
